### ISSUE TITLE
Unable to read digital inputs/outputs

### ISSUE THREAD

**Issue by dshatohin** [RichiH/modbus_exporter#10]
Hi,
Trying to read 1 register from 1xxxx or 2xxxx "address-space" but getting error:
`insufficient amount of registers provided: expected at least 1, got 1`
How can I read 2 and more registers from 1xxxx or 2xxxx?

**Comment by dshatohin** [comment]
Sill can't figure it out. 
In file [modbus.go](https://github.com/RichiH/modbus_exporter/blob/master/modbus/modbus.go#L270) I found this line:
`// TODO: Maybe we don't need two registers for bool.`
Is it possible to read coils by this exporter?
Or maybe my modbus.yml isn't correct?
```
modules:

    - name: "testcoils"
      protocol: 'tcp/ip'
      metrics:
        - name: "availability"
          help: "Availability of modbus-unit"
          address: 10001
          bitOffset: 0
          dataType: bool
          metricType: gauge
```
And there is no examples of ReadCoils config in [example modbus.yml file](https://github.com/RichiH/modbus_exporter/blob/master/modbus.yml)
