### ISSUE TITLE
Allow addressing by ID instead of "analog input" etc

### ISSUE THREAD

**Issue by RichiH** [RichiH/modbus_exporter#2]
@mxinden

A default config should probably come with comments to allow people familiar with Modbus to know where to put things in the config and keep a mental map. That being said, addressing by "coil" and other such names seems cumbersome and error-prone. Addressing by ID directly seems better.

Sub-addressing could be done by `id:bit`, ranges could be done explicitly by `id-idN` or implicitly by `id, float32, little endian`.

Gut feeling is that we will develop stronger opinions when using it for some time.

**Comment by RichiH** [comment]
@mxinden This is not yet done, correct?

**Comment by RichiH** [comment]
Seems it's not, yet.

CC @bastischubert

**Comment by RichiH** [comment]
Disregarding that joule as an absolute would be better as we can calculate Wh as a `rate()` from there, I think this would be the better model. Current style:

````
  - name: 'dcim_power_consumption-xxx'
    protocol: 'tcp/ip'
    id: 2
    analogOut:
      - name: power_consumed_watt_hours
        help: 'Power Consumtion in WattHours'
        address: 1226
        metricType: counter
        labels:
          datacenter: 'Halma'
          room: 'xx'
          rack: 'xx'
          fuse: 'xx'
          customer: 'xx'
          billable: 'xx'
        dataType: float32
````

Proposed new style:
````
pre-amble block for the whole target, or exporter instance
  - protocol: 'tcp/ip'
    id: 2 << what is this? Is it unique? Or can it go into pre-amble?

    address: 1226 << this could either be keyed by address, or name. But given that the address is static, it should most likely be keyed by address
        name: 'power_consumed_watt_hours'
        help: 'Power Consumtion in WattHours'
        metricType: counter
        dataType: float32
        labels:
          datacenter: 'xx'
          room: 'xx'
          rack: 'xx'
          fuse: 'xx'
          customer: 'xx'
          billable: 'xx'
````
