### ISSUE TITLE
Inverter Huawei SUN2000, scrape i/o timeout

### ISSUE THREAD

**Issue by maleksan** [RichiH/modbus_exporter#38]
Inverter Huawei SUN2000, scrape i/o timeout.

Trying to read modbus(Inverter Huawei SUN2000) "Active Power" data, but there is such error:
```code
time="2023-02-02T14:14:56Z" level=info msg="got scrape request for module 'fake' target '<modbus_ip_adress>:1502' and sub_target '2'" source="modbus_exporter.go:81"
time="2023-02-02T14:15:01Z" level=error msg="failed to scrape metrics for module 'fake': metric 'active_power', address '32080': read tcp ****:33534-><<modbus_ip_adress>>:1502: i/o timeout" source="modbus_exporter.go:96"
```

modbus.yml cofig:
```yaml
modules:
  # Module name, needs to be passed as parameter by Prometheus.
  - name: 'fake'
    protocol: 'tcp/ip'
    metrics:
      # Name of the metric.
      - name: 'active_power'
        help: 'active power'
        address: 32080
        dataType: int32
        metricType: gauge
```

Modbus unitid is 2.

Url:
```code
http://localhost:9602/modbus?target=<modbus_ip_adress>:1502&module=fake&sub_target=2
```

Modbus unit port is open:
```bash
nc -zv <modbus_ip_adress> 1502
Connection to <modbus_ip_adress> 1502 port [tcp/*] succeeded!
```

Huawei register definitions documentation says the following:
![image](https://user-images.githubusercontent.com/73186636/216355157-369acca9-0665-46f4-b5ac-f368d850c434.png)

What is wrong in my configuration?
In the meantime, I can read Modbus data with the Node-red module - https://flows.nodered.org/node/node-red-contrib-modbus
