### ISSUE TITLE
Ability to flip coil values

### ISSUE THREAD

**Issue by DaAwesomeP** [RichiH/modbus_exporter#55]
It would be great to have an option to flip coil/bool values like `invert: True`

Example:
```yaml
modules:
  - name: "fake"
    protocol: 'tcp/ip'
    metrics:
      - name: "coil"
        help: "some help for some coil"
        address: 124
        dataType: bool
        bitOffset: 0
        metricType: gauge
        invert: True # 1 becomes 0, 0 becomes 1
```
