### ISSUE TITLE
Wrong values when reading SMA inverter

### ISSUE THREAD

**Issue by LukeLR** [RichiH/modbus_exporter#61]
Hi, thanks for this great project. I want to create an SMA inverter config, but I'm failing to read registers.

[SMA Modbus TCP documentation](https://files.sma.de/downloads/PARAMETER-HTML_STPxx-3SE-40_30109R_V11.zip) taken from [here](https://www.sma.de/produkte/hybrid-wechselrichter/sunny-tripower-smart-energy) lists e.g. register 31435 as a signed int32 value, sub_device is 3 (SMA default). Reading this register using pymodbus or qmodmaster gives two 16bit values 0, 1716. However, reading the register using 

```
http://localhost:9602/modbus?target=10.10.4.225:502&module=SMA&sub_target=3
```

with modbus_exporter always gives me:

```
# HELP power_consumption_total represents the overall power consumption by phase
# TYPE power_consumption_total gauge
power_consumption_total{module="SMA",phase="1"} -1
```

Changing endianness doesn't seem to do anything. Am I doing something wrong? Here's my config:

```
modules:

    # Module name, needs to be passed as parameter by Prometheus.
  - name: "SMA"
    protocol: 'tcp/ip'
    metrics:
        # Name of the metric.
      - name: "power_consumption_total"
        # Help text of the metric.
        help: "represents the overall power consumption by phase"
        # Labels to be added to the time series.
        labels:
          phase: "1"
        # Register address.
        # The first digit of the address is the function code
        # Supported codes are: 1, 2, 3, 4
        address: 31435
        # Datatypes allowed: bool, int16, int32, int64, uint16, uint32, uint64,
        #   float16, float32, float64
        # One register holds 16 bits.
        dataType: int32
        # Endianness allowed: big, little, mixed, yolo
        # Optional. If not defined: big.
        endianness: big
        # Prometheus metric type: https://prometheus.io/docs/concepts/metric_types/.
        metricType: gauge
        # Factor can be specified to represent metric value.
        # Examples: 1, 2, 1.543, 0.01 etc
        # Factor is multiplied with the scraped value to produce the metric value
        # Optional.
```

Any ideas appreciated!
