### ISSUE TITLE
Data is not properly collected

### ISSUE THREAD

**Issue by JesusFrontelo** [RichiH/modbus_exporter#76]
Good Afternoon, 

When I try to get the data from the records of my Ingecon inverter from the modbus exporter I see that the values obtained are not correct. For example, the first 6 records correspond to the date (year, month, day, hour, minutes, and seconds). In modbus-exporter I am getting the value 2024 for all of them, but if I set a flow to node-red I get the data correctly. 

This is the data i get from modbus-exporter:
![image](https://github.com/user-attachments/assets/18534727-8398-4640-ab2a-57306ea9f101)

And this is the configuration at modbus.yml:

```
modules:

  - name: "start"
    protocol: 'tcp/ip'
    metrics:

      - name: "ModBus_Actual_Year"
        help: "Actual Date. Year (Uint16)"
        address: 30000
        dataType: uint16
        endianness: big
        metricType: gauge
        labels:
          address: 30000

      - name: "ModBus_Actual_Month"
        help: "Actual Date. Month (Uint16)"
        address: 30001
        dataType: uint16
        metricType: gauge
        endianness: big
        labels:
          address: 30001

      - name: "ModBus_Actual_Day"
        help: "Actual Date. Day (Uint16)"
        address: 30002
        dataType: uint16
        metricType: gauge
        endianness: big
        labels:
          address: 30002

....
```

This is the data i obtanined at node-red:

![image](https://github.com/user-attachments/assets/9ce8078f-a881-4461-a9ab-fbe351f2e142)

The configuration at buffer parser is:

![image](https://github.com/user-attachments/assets/0c68d5f5-7a26-48cb-b674-6d823d148149)

I think it would be necessary to add the offset byte option to the metrics settings as you can see in Node-Red's parser buffer so that you can get the data correctly with Node-Exporter.

Hope someone can help me. 

Regards.
